Constructing a vqa model
Getting an error when saving & loading, need to refactor to fluent API
The error:

in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 10 layers into a model with 2 layers.